apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # Set the target port based on your application
  type: LoadBalancer  # Use "LoadBalancer" type for cloud deployments; for local testing, use "NodePort"
